name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      # TODO: add a build step here
      - name: Build Deploy
        run: |
          deno --version
          deno install --unstable --allow-read --allow-write --allow-net --allow-env --allow-run --name=pagic https://deno.land/x/pagic@v1.6.2/mod.ts
          pagic build

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "strong-fly-19"
          entrypoint: "./main.ts" # TODO: update entrypoint
